export default [
  {
    path: '/login',
    layout: false,
    name: 'login',
    component: './login',
    hideInMenu: true,
  },
  {
    path: '/welcome',
    name: 'welcome',
    icon: 'smile',
    component: './Welcome',
  },
  {
    name: 'dashboard',
    icon: 'table',
    path: '/dashboard',
    component: './dashboard',
  },
  {
    name: 'app',
    icon: 'table',
    path: '/app',
    component: './app',
  },
  {
    name: 'appMonitor',
    icon: 'table',
    path: '/app/monitor',
    component: './app/monitor',
    hideInMenu: true,
  },
  {
    name: 'job',
    icon: 'table',
    path: '/job',
    component: './job',
  },
  {
    name: 'jobMonitor',
    icon: 'table',
    path: '/job/monitor',
    component: './job/monitor',
    hideInMenu: true,
  },
  {
    name: 'alarm',
    icon: 'table',
    path: '/alarm',
    component: './alarm',
  },
  {
    name: 'user',
    icon: 'table',
    path: '/user',
    component: './user',
  },
  {
    name: 'logger',
    icon: 'smile',
    path: 'logger',
    component: './logger',
    hideInMenu: true,
  },
  {
    name: 'executor',
    icon: 'table',
    path: '/executor',
    component: './executor',
    hideInMenu: true,
  },
  {
    name: 'executorMonitor',
    icon: 'table',
    path: '/executor/monitor',
    component: './executor/monitor',
    hideInMenu: true,
  },
  {
    path: '/',
    redirect: '/welcome',
  },
  {
    component: './404',
  },
];
